FROM python:3.10

ARG benchmark
ARG service

RUN apt -y update && \
    apt -y upgrade && \
    apt install -y build-essential libssl-dev libffi-dev && \
    apt install -y git

WORKDIR /app

COPY ./${benchmark}/base_requirements.txt ./base_requirements.txt

RUN pip install -r base_requirements.txt
RUN pip install opentelemetry-distro opentelemetry-exporter-otlp
RUN opentelemetry-bootstrap -a install

COPY ./${benchmark}/services/${service} .
COPY ./${benchmark}/networking.json ./networking.json
COPY ./helper.py ./helper.py

ENTRYPOINT [ "opentelemetry-instrument" ]

ENV SERVICE=${service}
CMD python -m ${SERVICE}.app
