version: '3'

services:
    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - "16686:16686"

    movies:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-6:movies
        build:
            context: './services/movies/'
            dockerfile: './Dockerfile'
        ports:
            - "5001:5001"
    showtimes:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-6:showtimes
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: './services/showtimes'
            dockerfile: './Dockerfile'
        ports:
            - "5002:5002"
    bookings-primary:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-6:bookings-primary
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: './services/bookings-primary'
            dockerfile: './Dockerfile'
        ports:
            - "5003:5003"
    bookings-secondary:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-6:bookings-secondary
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: './services/bookings-secondary'
            dockerfile: './Dockerfile'
        ports:
            - "5004:5004"
    users:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-6:users
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: './services/users'
            dockerfile: './Dockerfile'
        ports:
            - "5000:5000"
