version: '3'

services:
    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - "16686:16686"

    api-gateway:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/expedia:api-gateway
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DEBUG
            - FLASK_DEBUG
        build:
            context: './services/api-gateway/'
            dockerfile: './Dockerfile'
        ports:
            - "5000:5000"
    review-ml:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/expedia:review-ml
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DEBUG
            - FLASK_DEBUG
        build:
            context: './services/review-ml'
            dockerfile: './Dockerfile'
        ports:
            - "5001:5001"
    review-time:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/expedia:review-time
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DEBUG
            - FLASK_DEBUG
        build:
            context: './services/review-time'
            dockerfile: './Dockerfile'
        ports:
            - "5002:5002"
