version: '3'

services:
    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - "16686:16686"

    orders:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/case-study-2-food-delivery-example-f:orders
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: './services/orders/'
            dockerfile: './Dockerfile'
        ports:
            - "5000:5000"
    delivery_auth:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/case-study-2-food-delivery-example-f:auth
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: './services/auth/'
            dockerfile: './Dockerfile'
        ports:
            - "5001:5001"
