version: '3'

services:
    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - "16686:16686"

    orders:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/case-study-1-food-delivery-example-1:orders
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DEBUG
            - FLASK_DEBUG
        build:
            context: './services/orders/'
            dockerfile: './Dockerfile'
        ports:
            - "5000:5000"
    auth:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/case-study-1-food-delivery-example-1:auth
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DEBUG
            - FLASK_DEBUG
        build:
            context: './services/auth'
            dockerfile: './Dockerfile'
        ports:
            - "5001:5001"
