version: '3'

services:
    movies:
        build:
            context: '../'
            dockerfile: './Dockerfile.python.service'
            args:
                benchmark: cinema-3
                service: movies
        ports:
            - "5001:5001"
    showtimes:
        build:
            context: '../'
            dockerfile: './Dockerfile.python.service'
            args:
                benchmark: cinema-3
                service: showtimes
        ports:
            - "5002:5002"
    bookings:
        build:
            context: '../'
            dockerfile: './Dockerfile.python.service'
            args:
                benchmark: cinema-3
                service: bookings
        ports:
            - "5003:5003"
    users:
        build:
            context: '../'
            dockerfile: './Dockerfile.python.service'
            args:
                benchmark: cinema-3
                service: users
        ports:
            - "5000:5000"
