services:
  movies-proxy:
    image: fit-proxy:latest
    environment:
    - ORCHESTRATOR_HOST=orchestrator:5000
    - CONTROLLER_PORT=8050
    - SERVICE_NAME=movies
    - PROXY_HOST=0.0.0.0:5001
    - PROXY_TARGET=http://movies-real:5001
    hostname: movies
    ports:
    - 5001:5001
  movies-real:
    build:
      context: ../
      dockerfile: ./Dockerfile.python.service
      args:
        benchmark: cinema-3
        service: movies
    hostname: movies-real
    environment:
    - OTEL_SERVICE_NAME=movies
    - OTEL_TRACES_EXPORTER=otlp
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    - FLASK_DEBUG
  showtimes-proxy:
    image: fit-proxy:latest
    environment:
    - ORCHESTRATOR_HOST=orchestrator:5000
    - CONTROLLER_PORT=8050
    - SERVICE_NAME=showtimes
    - PROXY_HOST=0.0.0.0:5002
    - PROXY_TARGET=http://showtimes-real:5002
    hostname: showtimes
    ports:
    - 5002:5002
  showtimes-real:
    build:
      context: ../
      dockerfile: ./Dockerfile.python.service
      args:
        benchmark: cinema-3
        service: showtimes
    hostname: showtimes-real
    environment:
    - OTEL_SERVICE_NAME=showtimes
    - OTEL_TRACES_EXPORTER=otlp
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    - FLASK_DEBUG
  bookings-proxy:
    image: fit-proxy:latest
    environment:
    - ORCHESTRATOR_HOST=orchestrator:5000
    - CONTROLLER_PORT=8050
    - SERVICE_NAME=bookings
    - PROXY_HOST=0.0.0.0:5003
    - PROXY_TARGET=http://bookings-real:5003
    hostname: bookings
    ports:
    - 5003:5003
  bookings-real:
    build:
      context: ../
      dockerfile: ./Dockerfile.python.service
      args:
        benchmark: cinema-3
        service: bookings
    hostname: bookings-real
    environment:
    - OTEL_SERVICE_NAME=bookings
    - OTEL_TRACES_EXPORTER=otlp
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    - FLASK_DEBUG
  users-proxy:
    image: fit-proxy:latest
    environment:
    - ORCHESTRATOR_HOST=orchestrator:5000
    - CONTROLLER_PORT=8050
    - SERVICE_NAME=users
    - PROXY_HOST=0.0.0.0:5000
    - PROXY_TARGET=http://users-real:5000
    hostname: users
    ports:
    - 5000:5000
  users-real:
    build:
      context: ../
      dockerfile: ./Dockerfile.python.service
      args:
        benchmark: cinema-3
        service: users
    hostname: users-real
    environment:
    - OTEL_SERVICE_NAME=users
    - OTEL_TRACES_EXPORTER=otlp
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    - FLASK_DEBUG
  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
    - 16686:16686
    environment:
    - COLLECTOR_OTLP_ENABLED=true
  orchestrator:
    image: fit-orchestrator:latest
    ports:
    - 6050:5000
    environment:
    - PROXY_LIST=movies:8050,showtimes:8050,bookings:8050,users:8050
