version: '3'

services:
    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - "16686:16686"

    movies:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-4:movies
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DEBUG
            - FLASK_DEBUG
        build:
            context: './services/movies/'
            dockerfile: './Dockerfile'
        ports:
            - "5001:5001"
    showtimes:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-4:showtimes
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DEBUG
            - FLASK_DEBUG
        build:
            context: './services/showtimes'
            dockerfile: './Dockerfile'
        ports:
            - "5002:5002"
    bookings:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-4:bookings
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DEBUG
            - FLASK_DEBUG
        build:
            context: './services/bookings'
            dockerfile: './Dockerfile'
        ports:
            - "5003:5003"
    users:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-4:users
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DEBUG
            - FLASK_DEBUG
        build:
            context: './services/users'
            dockerfile: './Dockerfile'
        ports:
            - "5000:5000"
