version: '3'

services:
    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - "16686:16686"

    load-balancer:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/mailchimp:load-balancer
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: './services/load-balancer/'
            dockerfile: './Dockerfile'
        ports:
            - "5000:5000"
    app-server:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/mailchimp:app-server
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: './services/app-server'
            dockerfile: './Dockerfile'
        ports:
            - "5001:5001"
    requestmapper:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/mailchimp:requestmapper
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: './services/requestmapper'
            dockerfile: './Dockerfile'
        ports:
            - "5002:5002"
    db-primary:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/mailchimp:db-primary
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: './services/db-primary'
            dockerfile: './Dockerfile'
        ports:
            - "5003:5003"
    db-secondary:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/mailchimp:db-secondary
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: './services/db-secondary'
            dockerfile: './Dockerfile'
        ports:
            - "5004:5004"
